---
- name: Add Wide IP to multiple F5 BIG-IP servers
  hosts: localhost
  gather_facts: no
  vars:
    f5_servers:
      - { server: "121.78.62.82", user: "hdg7025", password: "^kdgksrk30%" }
      - { server: "118.221.123.42", user: "hdg7025", password: "^kdgksrk30%" }
      - { server: "139.150.254.194", user: "hdg7025", password: "^kdgksrk30%" }

  tasks:
    - name: Set lb method on F5 BIG-IP
      bigip_gtm_wide_ip:
        pool_lb_mothod: round-robin
        pools:
          - name: "{{ pool }}"
        name: "{{ name }}"
        type: "{{ type }}"
        provider:
          server: "{{ item.server }}"
          user: "{{ item.user }}"
          password: "{{ item.password }}"
          validate_certs: no
        state: present
      loop: "{{ f5_servers }}"
      delegate_to: localhost
