---
- name: Add Wide IP to multiple F5 BIG-IP servers
  hosts: localhost
  gather_facts: no
  vars:
    f5_servers:
      - { server: "121.78.62.82", user: "admin", password: "secret" }
      - { server: "118.221.123.42", user: "admin", password: "secret" }
      - { server: "139.150.254.194", user: "admin", password: "secret" }
    wide_ip_name: "{{ wide_ip_name }}"
    wide_ip_type: "{{ wide_ip_type }}"
    pool_lb_method: round-robin

  tasks:
    - name: Set lb method on F5 BIG-IP
      bigip_gtm_wide_ip:
        pool_lb_method: "{{ pool_lb_method }}"
        name: "{{ wide_ip_name }}"
        type: "{{ wide_ip_type }}"
        provider:
          server: "{{ item.server }}"
          user: "{{ item.user }}"
          password: "{{ item.password }}"
          validate_certs: no
        state: present
      loop: "{{ f5_servers }}"
      delegate_to: localhost
