- name: Fetch and display GTM pool list with members
  collections:
    - community.general
  hosts: localhost
  gather_facts: no
  vars:
    pool_name: "donggyu"
    server_ip: "139.150.254.31"
  tasks:
    - name: Fetch GTM pool list
      uri:
        url: "https://139.150.254.31/mgmt/tm/gtm/pool/a"
        method: GET
        return_content: yes
        user: "hdg7025"
        password: "^kdgksrk30%"
        headers:
          Accept: "application/json"
        validate_certs: no
      register: gtm_pool_response

    - name: Extract pool details using json_query with filter
      set_fact:
        filtered_pools: >-
          {{
            gtm_pool_response.json | json_query("items[?contains(name, '" ~ pool_name ~ "')].{name: name, members_link: membersReference.link}")
          }}

    - name: Ensure filtered_pools is a list
      set_fact:
        filtered_pools: "{{ filtered_pools | default([]) | list }}"

    - name: Initialize filtered_pools_with_links
      set_fact:
        filtered_pools_with_links: []

    - name: Replace 'localhost' with server_ip in members_link
      set_fact:
        filtered_pools_with_links: "{{ filtered_pools_with_links + [{'name': item.name, 'members_link': (item.members_link | replace('localhost', server_ip))}] }}"
      loop: "{{ filtered_pools }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Debug filtered pools with updated links
      debug:
        msg: "{{ filtered_pools_with_links }}"
