- name: Delete Wide IP on BIG-IP GTM
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Delete a Wide IP
      f5networks.f5_modules.bigip_gtm_wide_ip:
        provider:
          server: "139.150.254.31"
          user: "hdg7025"
          password: "^kdgksrk30%"
          validate_certs: no
        name: "{{ gtm_domain }}"
        type: a
        partition: "Common"
        state: "absent"
