- name: Create Wide IP
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create a Wide IP on BIG-IP GTM
      f5networks.f5_modules.bigip_gtm_wide_ip:
        provider:
          server: "139.150.254.31"
          user: "hdg7025"
          password: "^kdgksrk30%"
          validate_certs: false
        name: "donggyu.test.kinxcdn.com"
        partition: "Common"
        pool_lb_mode: "round-robin"
        pools:
          - name: "raptor_dlt_all"
        state: "present"
