- name: Create Wide IP on BIG-IP GTM
  hosts: localhost
  gather_facts: no
  vars:
    gtm_pools: >
      {{
        [
          {"name": pool_1} if pool_1 is defined and pool_1 != "" else None,
          {"name": pool_2} if pool_2 is defined and pool_2 != "" else None,
          {"name": pool_3} if pool_3 is defined and pool_3 != "" else None
        ] | select("not none") | list
      }}
  tasks:
    - name: Create a Wide IP
      f5networks.f5_modules.bigip_gtm_wide_ip:
        provider:
          server: "139.150.254.31"
          user: "hdg7025"
          password: "^kdgksrk30%"
          validate_certs: false
        name: "donggyutest.aaa.kkk"
        type: a
        partition: "Common"
        pool_lb_method: "round-robin"
        pools: "{{ gtm_pools }}"
        state: "present"
