---
- name: Fetch and display filtered Wide IP list
  hosts: localhost
  gather_facts: no
  vars:
    wideip_name: "{{ wideip_name }}"  # 설문조사를 통해 사용자로부터 입력받은 값

  tasks:
    - name: Fetch Wide IP list
      uri:
        url: "https://139.150.254.31/mgmt/tm/gtm/wideip/a"
        method: GET
        user: "hdg7025"
        password: "^kdgksrk30%"
        validate_certs: no
      register: wideip_list

    - name: Verify the structure of wideip_list
      debug:
        var: wideip_list.json

    - name: Ensure items is defined
      set_fact:
        wideip_items: "{{ wideip_list.json.items }}"

    - name: Filter Wide IP list
      set_fact:
        filtered_wideip_list: "{{ wideip_items | selectattr('name', 'defined') | selectattr('name', 'search', wideip_name) | list }}"
      when: wideip_items is defined

    - name: Display filtered Wide IP list
      debug:
        var: filtered_wideip_list
      when: filtered_wideip_list is defined
