- name: Fetch and display specific GTM pool with members
  collections:
    - community.general
  hosts: localhost
  gather_facts: no
  vars:
    pool_name: "{{ pool_name }}"  # 설문조사에서 입력받을 변수 (AWX에서 설정)
  tasks:
    - name: Fetch GTM pool list
      uri:
        url: "https://139.150.254.31/mgmt/tm/gtm/pool/a"
        method: GET
        return_content: yes
        user: "hdg7025"               # 사용자 ID
        password: "^kdgksrk30%"       # 비밀번호
        headers:
          Accept: "application/json"  # 응답으로 JSON을 받기 위해 설정
        validate_certs: no
      register: gtm_pool_response

    - name: Extract pool details containing pool_name using json_query
      set_fact:
        selected_pool: >-
          {{ gtm_pool_response.json.items |
             json_query("[?name == '" ~ pool_name ~ "']") | first }}

    - name: Check if pool exists
      fail:
        msg: "No pool found with the name {{ pool_name }}"
      when: selected_pool is not defined

    - name: Fetch members for the selected pool
      uri:
        url: "{{ selected_pool.membersReference.link }}"
        method: GET
        return_content: yes
        user: "hdg7025"               # 사용자 ID
        password: "^kdgksrk30%"       # 비밀번호
        headers:
          Accept: "application/json"  # 응답으로 JSON을 받기 위해 설정
        validate_certs: no
      register: pool_members_response
      when: selected_pool.membersReference.link is defined

    - name: Set fact for pool members
      set_fact:
        pool_members: "{{ pool_members_response.json.items | map(attribute='name') | list }}"
      when: selected_pool.membersReference.link is defined

    - name: Display pool details with members
      debug:
        msg: "Pool name: {{ selected_pool.name }}, Members: {{ pool_members }}"
