- name: Fetch and display GTM pool list
  collections:
    - community.general
  hosts: localhost
  gather_facts: no
  vars:
    pool_name: "{{ pool_name }}"  # 설문조사에서 입력받을 변수 (AWX에서 설정)
  tasks:
    - name: Fetch GTM pool list
      uri:
        url: "https://139.150.254.31/mgmt/tm/gtm/pool/a"
        method: GET
        return_content: yes
        user: "hdg7025"               # 사용자 ID
        password: "^kdgksrk30%"       # 비밀번호
        headers:
          Accept: "application/json"  # 응답으로 JSON을 받기 위해 설정
        validate_certs: no
      register: gtm_pool_response

    - name: Extract pool details using json_query with filter
      set_fact:
        pool_details: >-
          {{ gtm_pool_response.json |
             json_query("items[?contains(name, '" ~ pool_name ~ "')].{name: name}") }}

    - name: Display pool details
      debug:
        msg: "{{ pool_details }}"
