- name: Fetch and display GTM server list
  collections:
    - community.general
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Fetch WideipList
      uri:
        url: "https://139.150.254.31/mgmt/tm/gtm/server"
        method: GET
        return_content: yes
        user: "hdg7025"               # 사용자 ID
        password: "^kdgksrk30%"       # 비밀번호
        headers:
          Accept: "application/json"  # 응답으로 JSON을 받기 위해 설정
        validate_certs: no
      register: gtm_servers_response

    - name: Extract server details using json_query with filter
      set_fact:
        server_details: >-
          {{ gtm_servers_response.json |
             json_query("items[?contains(name, 'donggyu')].{name: name, addresses: addresses[*].name}") }}

    - name: Display server details
      debug:
        msg: "{{ server_details }}"
