- name: Filter Wide IP list based on search query
  hosts: localhost
  gather_facts: no
  vars:
    search_query: "{{ search_query }}"  
  tasks:
    - name: Fetch Wide IP list
      uri:
        url: "https://139.150.254.31/mgmt/tm/gtm/wideip/a"
        method: GET
        user: "hdg7025"
        password: "^kdgksrk30%"
        validate_certs: no
      register: wideip_list

    - name: Filter and display Wide IPs
      debug:
        msg: >
          {%- set result = [] -%}
          {%- for item in wideip_list.json.items -%}
            {%- if search_query in item.name -%}
              {%- set pools = item.pools | default([]) | map(attribute='name') | list -%}
              {%- set pools_cname = item.poolsCname | default([]) | map(attribute='name') | list -%}
              {%- set _ = result.append({ 'Wide IP Name': item.name, 'Pools': pools, 'Pools CNAME': pools_cname }) -%}
            {%- endif -%}
          {%- endfor -%}
          {{ result }}
