---
- name: Configure Wide IP on F5 BIG-IP
  hosts: localhost
  gather_facts: no
  vars:
    f5_server: "139.150.254.31"
    f5_user: "hdg7025"
    f5_password: "^kdgksrk30%"
    gtm_name: donggyutest.kinx.com
    gtm_type: a
    gtm_pool: raptor_dlt_all
  tasks:
    - name: Create Wide IP
      bigip_gtm_wide_ip:
        name: "{{ gtm_name }}"
        type: "{{ gtm_type }}"
        pool_lb_method: round-robin
        pools:
          - name: "{{ gtm_pool }}"
        provider:
          server: "{{ f5_server }}"
          user: "{{ f5_user }}"
          password: "{{ f5_password }}"
          validate_certs: no
        
  
