---
- name: create wideiplist
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create Wide IP
      bigip_gtm_wide_ip:
        name: "{{ gtm_name }}"
        type: "{{ gtm_type }}"
        pool_lb_method: round-robin
        pools:
          - name: "{{ gtm_pool }}"
            ratio: 1
        provider:
          server: 139.150.254.31
          user: hdg7025
          password: ^kdgksrk30%
          validate_certs: no
        
  
