---
- name: Configure Wide IP on F5 BIG-IP
  hosts: localhost
  gather_facts: no
  vars:
    f5_server: "118.221.123.43"
    f5_user: "hdg7025"
    f5_password: "^kdgksrk30%"
  tasks:
    - name: Create Wide IP
      bigip_gtm_wide_ip:
        name: "{{ name }}"
        type: "{{ type }}"
        pool_lb_method: round-robin
        pools:
          - name: "{{ pool }}"
        provider:
          server: "{{ f5_server }}"
          user: "{{ f5_user }}"
          password: "{{ f5_password }}"
          validate_certs: no
        
  
